language: node_js
sudo: required
node_js:
  - '8.11.1'
  
notifications:
  slack: focallocal:njis5lKnuOTF1dp8W7HiTn8I
      
cache:
  directories:
    - $HOME/.meteor

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Remove cache if the project is upgraded to a newer version of meteor
  - export PATH="$HOME/.meteor:$PATH"
  - openssl enc -d -aes-256-cbc -md md5 -in deploy.tar.enc -out deploy.tar -k "$encrypted_key_master"
  - openssl enc -d -aes-256-cbc -md md5 -in secrets.tar.enc -out secrets.tar -k "$encrypted_key_master"
  - tar xf secrets.tar
  - tar xzf deploy.tar
  - npm install -g mup
  - curl https://install.meteor.com/?release=1.6.1.1 | /bin/sh

branches:
  only:
    - master
    - fl-sleeper

script:
  #- npm test
  - mup setup
  - mup deploy